/* eslint-disable */
// This file is auto-generated by TanStack Router.
// A minimal seed tree is provided so the project builds before `pnpm dev` regenerates it.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as LoginRoute } from "./routes/login";
import { Route as SignupRoute } from "./routes/signup";
import { Route as DashboardRoute } from "./routes/dashboard";
import { Route as ChatRoute } from "./routes/chat";
import { Route as SettingsRoute } from "./routes/settings";
import { Route as AdminIndexRoute } from "./routes/admin/index";
import { Route as AdminBlogIndexRoute } from "./routes/admin/blog/index";
import { Route as AdminBlogNewRoute } from "./routes/admin/blog/new";
import { Route as AdminBlogIdRoute } from "./routes/admin/blog/$id";

const IndexR = IndexRoute.update({ id: "/", path: "/", getParentRoute: () => rootRoute } as any);
const LoginR = LoginRoute.update({ id: "/login", path: "/login", getParentRoute: () => rootRoute } as any);
const SignupR = SignupRoute.update({ id: "/signup", path: "/signup", getParentRoute: () => rootRoute } as any);
const DashboardR = DashboardRoute.update({ id: "/dashboard", path: "/dashboard", getParentRoute: () => rootRoute } as any);
const ChatR = ChatRoute.update({ id: "/chat", path: "/chat", getParentRoute: () => rootRoute } as any);
const SettingsR = SettingsRoute.update({ id: "/settings", path: "/settings", getParentRoute: () => rootRoute } as any);
const AdminIndexR = AdminIndexRoute.update({ id: "/admin/", path: "/admin/", getParentRoute: () => rootRoute } as any);
const AdminBlogIndexR = AdminBlogIndexRoute.update({ id: "/admin/blog/", path: "/admin/blog/", getParentRoute: () => rootRoute } as any);
const AdminBlogNewR = AdminBlogNewRoute.update({ id: "/admin/blog/new", path: "/admin/blog/new", getParentRoute: () => rootRoute } as any);
const AdminBlogIdR = AdminBlogIdRoute.update({ id: "/admin/blog/$id", path: "/admin/blog/$id", getParentRoute: () => rootRoute } as any);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { id: "/"; path: "/"; fullPath: "/"; preLoaderRoute: typeof IndexRoute; parentRoute: typeof rootRoute };
    "/login": { id: "/login"; path: "/login"; fullPath: "/login"; preLoaderRoute: typeof LoginRoute; parentRoute: typeof rootRoute };
    "/signup": { id: "/signup"; path: "/signup"; fullPath: "/signup"; preLoaderRoute: typeof SignupRoute; parentRoute: typeof rootRoute };
    "/dashboard": { id: "/dashboard"; path: "/dashboard"; fullPath: "/dashboard"; preLoaderRoute: typeof DashboardRoute; parentRoute: typeof rootRoute };
    "/chat": { id: "/chat"; path: "/chat"; fullPath: "/chat"; preLoaderRoute: typeof ChatRoute; parentRoute: typeof rootRoute };
    "/settings": { id: "/settings"; path: "/settings"; fullPath: "/settings"; preLoaderRoute: typeof SettingsRoute; parentRoute: typeof rootRoute };
    "/admin/": { id: "/admin/"; path: "/admin"; fullPath: "/admin"; preLoaderRoute: typeof AdminIndexRoute; parentRoute: typeof rootRoute };
    "/admin/blog/": { id: "/admin/blog/"; path: "/admin/blog"; fullPath: "/admin/blog"; preLoaderRoute: typeof AdminBlogIndexRoute; parentRoute: typeof rootRoute };
    "/admin/blog/new": { id: "/admin/blog/new"; path: "/admin/blog/new"; fullPath: "/admin/blog/new"; preLoaderRoute: typeof AdminBlogNewRoute; parentRoute: typeof rootRoute };
    "/admin/blog/$id": { id: "/admin/blog/$id"; path: "/admin/blog/$id"; fullPath: "/admin/blog/$id"; preLoaderRoute: typeof AdminBlogIdRoute; parentRoute: typeof rootRoute };
  }
}

export const routeTree = rootRoute.addChildren([
  IndexR,
  LoginR,
  SignupR,
  DashboardR,
  ChatR,
  SettingsR,
  AdminIndexR,
  AdminBlogIndexR,
  AdminBlogNewR,
  AdminBlogIdR,
]);
